Traceback (most recent call last):
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\wsaye\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\wsaye\PycharmProjects\CashAppInterview\venv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# in Python
test_date_str = "2022-01-01"
test_dt = dt.datetime.strptime(test_date_str, "%Y-%m-%d")
print(test_dt + dt.timedelta(days=2))
print(new_date + relativedelta(years=5, months=4))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[20], line 5[0m
[0;32m      3[0m test_dt [38;5;241m=[39m dt[38;5;241m.[39mdatetime[38;5;241m.[39mstrptime(test_date_str, [38;5;124m"[39m[38;5;124m%[39m[38;5;124mY-[39m[38;5;124m%[39m[38;5;124mm-[39m[38;5;132;01m%d[39;00m[38;5;124m"[39m)
[0;32m      4[0m [38;5;28mprint[39m(test_dt [38;5;241m+[39m dt[38;5;241m.[39mtimedelta(days[38;5;241m=[39m[38;5;241m2[39m))
[1;32m----> 5[0m [38;5;28mprint[39m([43mnew_date[49m [38;5;241m+[39m relativedelta(years[38;5;241m=[39m[38;5;241m5[39m, months[38;5;241m=[39m[38;5;241m4[39m))

[1;31mNameError[0m: name 'new_date' is not defined
NameError: name 'new_date' is not defined

